/**
 *  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.                        *
 *                                                                                                 *
 *  Licensed under the Amazon Software License (the "License"). You may not use this               *
 *  file except in compliance with the License. A copy of the License is located at                *
 *                                                                                                 *
 *      http://aws.amazon.com/asl/                                                                 *
 *                                                                                                 *
 *  or in the "license" file accompanying this file. This file is distributed on an "AS IS"        *
 *  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or implied. See the License       *
 *  for the specific language governing permissions and limitations under the License.             *
 *
 */

/**
 * @author MediaEnt Solutions
 */

/* eslint-disable no-console */
/* eslint-disable no-unused-vars */

/**
 * @class IotSubscriber
 * @description managing Iot subscription and pump messages from state machines to webapp
  */
class IotSubscriber {
  constructor(cognito, collection) {
    try {
      if (!cognito) {
        throw new Error('missing parameter, cognito');
      }

      if (!collection) {
        throw new Error('missing parameter, collection');
      }

      this.$cognitoInstance = cognito;
      this.$collectionInstance = collection;
      this.$errorStatus = '#errorStatus';
      this.$iotInstance = undefined;
      this.$host = undefined;
      this.$topic = undefined;
      this.$clientId = undefined;
    } catch (e) {
      e.message = `IotSubscriber.constructor: ${e.message}`;
      console.error(e.message);
      throw e;
    }
  }

  get cognito() {
    return this.$cognitoInstance;
  }

  get collection() {
    return this.$collectionInstance;
  }

  get iot() {
    return this.$iotInstance;
  }

  set iot(val) {
    this.$iotInstance = val;
  }

  get region() {
    return this.$region;
  }

  get host() {
    return this.$host;
  }

  set host(val) {
    this.$host = val;
  }

  get topic() {
    return this.$topic;
  }

  set topic(val) {
    this.$topic = val;
  }

  get clientId() {
    return this.$clientId;
  }

  set clientId(val) {
    this.$clientId = val;
  }

  get errorStatus() {
    return this.$errorStatus;
  }

  /**
   * @function reconnect
   * @description reconnect to Iot message broker
   */
  async reconnect() {
    try {
      const {
        accessKeyId = '',
        secretAccessKey = '',
        sessionToken = '',
      } = AWS.config.credentials || {};
      console.log(`reconnecting ${this.clientId} with temporary credential...`);

      await this.iot.updateWebSocketCredentials(accessKeyId, secretAccessKey, sessionToken);

      return this;
    } catch (e) {
      e.message = `IotSubscriber.reconnect: ${e.message}`;
      console.error(e.message);
      return this;
    }
  }

  /**
   * @function connect
   * @description connecto Iot message broker
   */
  async connect() {
    try {
      if (!this.host || !this.topic) {
        /* solution-manifest.js is auto-generated by CloudFormation template */
        /* Global variable is the solution ID */
        const {
          DynamoDB: {
            Configuration: {
              Table,
              PartitionKey,
              ItemKey,
            },
          },
        } = SO0050;

        const {
          AWSomeNamespace: {
            DBConfig,
          },
        } = window;

        const config = await DBConfig.loadFromDB(Table, PartitionKey, ItemKey);

        this.host = config.iotHost;
        this.topic = config.iotStatusTopic;
      }

      const user = this.cognito.user || {};

      const {
        accessKeyId = '',
        secretAccessKey: secretKey = '',
        sessionToken = '',
      } = AWS.config.credentials || {};

      this.clientId = `${user.username || 'anonymous'}-${(Math.floor((Math.random() * 100000) + 1))}`;

      this.iot = AWSIoTData.device({
        host: this.host,
        region: AWS.config.region,
        clienId: this.clientId,
        protocol: 'wss',
        debug: false,
        accessKeyId,
        secretKey,
        sessionToken,
      });
    } catch (e) {
      e.message = `IotSubscriber.connect: ${e.message}`;
      console.error(e.message);
      return this;
    }

    this.iot.on('connect', () => {
      console.log(`${this.clientId} connected to IoT`);
      this.iot.subscribe(this.topic);
    });

    this.iot.on('reconnect', () => {
      console.log(`${this.clientId} reconnecting...`);
      this.reconnect();
    });

    this.iot.on('message', (topic, payload) => {
      const status = JSON.parse(payload.toString());
      const bindFn = this.delegate.bind(this, status);

      setTimeout(() => {
        bindFn();
      }, 10);
    });
    return this;
  }

  /**
   * @function delegate
   * @description delegate messages to CardCollection
   * @param {object} status
   */
  async delegate(status) {
    if (this.collection && typeof this.collection.messageHook === 'function') {
      await this.collection.messageHook(status);
    }
    return this;
  }
}
